#pragma warning disable 
namespace SPTSharp.Models.Eft.Common.Tables
{
    public class BotSettings
    {
        public Dictionary<string, BotType> types { get; set; } = new Dictionary<string, BotType>();
        public BotBase botBase { get; set; }
        public BotCore core { get; set; }
    }

    public class BotCore
    {
        public float SAVAGE_KILL_DIST { get; set; }
        public float SOUND_DOOR_BREACH_METERS { get; set; }
        public float SOUND_DOOR_OPEN_METERS { get; set; }
        public float STEP_NOISE_DELTA { get; set; }
        public float JUMP_NOISE_DELTA { get; set; }
        public float GUNSHOT_SPREAD { get; set; }
        public float GUNSHOT_SPREAD_SILENCE { get; set; }
        public float BASE_WALK_SPEREAD2 { get; set; }
        public float MOVE_SPEED_COEF_MAX { get; set; }
        public float SPEED_SERV_SOUND_COEF_A { get; set; }
        public float SPEED_SERV_SOUND_COEF_B { get; set; }
        public float G { get; set; }
        public float STAY_COEF { get; set; }
        public float SIT_COEF { get; set; }
        public float LAY_COEF { get; set; }
        public float MAX_ITERATIONS { get; set; }
        public float START_DIST_TO_COV { get; set; }
        public float MAX_DIST_TO_COV { get; set; }
        public float STAY_HEIGHT { get; set; }
        public float CLOSE_POINTS { get; set; }
        public float COUNT_TURNS { get; set; }
        public float SIMPLE_POINT_LIFE_TIME_SEC { get; set; }
        public float DANGER_POINT_LIFE_TIME_SEC { get; set; }
        public float DANGER_POWER { get; set; }
        public float COVER_DIST_CLOSE { get; set; }
        public float GOOD_DIST_TO_POINT { get; set; }
        public float COVER_TOOFAR_FROM_BOSS { get; set; }
        public float COVER_TOOFAR_FROM_BOSS_SQRT { get; set; }
        public float MAX_Y_DIFF_TO_PROTECT { get; set; }
        public float FLARE_POWER { get; set; }
        public float MOVE_COEF { get; set; }
        public float PRONE_POSE { get; set; }
        public float LOWER_POSE { get; set; }
        public float MAX_POSE { get; set; }
        public float FLARE_TIME { get; set; }
        public float MAX_REQUESTS__PER_GROUP { get; set; }
        public float UPDATE_GOAL_TIMER_SEC { get; set; }
        public float DIST_NOT_TO_GROUP { get; set; }
        public float DIST_NOT_TO_GROUP_SQR { get; set; }
        public float LAST_SEEN_POS_LIFETIME { get; set; }
        public float DELTA_GRENADE_START_TIME { get; set; }
        public float DELTA_GRENADE_END_TIME { get; set; }
        public float DELTA_GRENADE_RUN_DIST { get; set; }
        public float DELTA_GRENADE_RUN_DIST_SQRT { get; set; }
        public float PATROL_MIN_LIGHT_DIST { get; set; }
        public float HOLD_MIN_LIGHT_DIST { get; set; }
        public float STANDART_BOT_PAUSE_DOOR { get; set; }
        public float ARMOR_CLASS_COEF { get; set; }
        public float SHOTGUN_POWER { get; set; }
        public float RIFLE_POWER { get; set; }
        public float PISTOL_POWER { get; set; }
        public float SMG_POWER { get; set; }
        public float SNIPE_POWER { get; set; }
        public float GESTUS_PERIOD_SEC { get; set; }
        public float GESTUS_AIMING_DELAY { get; set; }
        public float GESTUS_REQUEST_LIFETIME { get; set; }
        public float GESTUS_FIRST_STAGE_MAX_TIME { get; set; }
        public float GESTUS_SECOND_STAGE_MAX_TIME { get; set; }
        public float GESTUS_MAX_ANSWERS { get; set; }
        public float GESTUS_FUCK_TO_SHOOT { get; set; }
        public float GESTUS_DIST_ANSWERS { get; set; }
        public float GESTUS_DIST_ANSWERS_SQRT { get; set; }
        public float GESTUS_ANYWAY_CHANCE { get; set; }
        public float TALK_DELAY { get; set; }
        public bool CAN_SHOOT_TO_HEAD { get; set; }
        public bool CAN_TILT { get; set; }
        public float TILT_CHANCE { get; set; }
        public float MIN_BLOCK_DIST { get; set; }
        public float MIN_BLOCK_TIME { get; set; }
        public float COVER_SECONDS_AFTER_LOSE_VISION { get; set; }
        public float MIN_ARG_COEF { get; set; }
        public float MAX_ARG_COEF { get; set; }
        public float DEAD_AGR_DIST { get; set; }
        public float MAX_DANGER_CARE_DIST_SQRT { get; set; }
        public float MAX_DANGER_CARE_DIST { get; set; }
        public float MIN_MAX_PERSON_SEARCH { get; set; }
        public float PERCENT_PERSON_SEARCH { get; set; }
        public float LOOK_ANYSIDE_BY_WALL_SEC_OF_ENEMY { get; set; }
        public float CLOSE_TO_WALL_ROTATE_BY_WALL_SQRT { get; set; }
        public float SHOOT_TO_CHANGE_RND_PART_MIN { get; set; }
        public float SHOOT_TO_CHANGE_RND_PART_MAX { get; set; }
        public float SHOOT_TO_CHANGE_RND_PART_DELTA { get; set; }
        public float FORMUL_COEF_DELTA_DIST { get; set; }
        public float FORMUL_COEF_DELTA_SHOOT { get; set; }
        public float FORMUL_COEF_DELTA_FRIEND_COVER { get; set; }
        public float SUSPETION_POINT_DIST_CHECK { get; set; }
        public float MAX_BASE_REQUESTS_PER_PLAYER { get; set; }
        public float MAX_HOLD_REQUESTS_PER_PLAYER { get; set; }
        public float MAX_GO_TO_REQUESTS_PER_PLAYER { get; set; }
        public float MAX_COME_WITH_ME_REQUESTS_PER_PLAYER { get; set; }
        public float CORE_POINT_MAX_VALUE { get; set; }
        public float CORE_POINTS_MAX { get; set; }
        public float CORE_POINTS_MIN { get; set; }
        public bool BORN_POISTS_FREE_ONLY_FAREST_BOT { get; set; }
        public bool BORN_POINSTS_FREE_ONLY_FAREST_PLAYER { get; set; }
        public bool SCAV_GROUPS_TOGETHER { get; set; }
        public float LAY_DOWN_ANG_SHOOT { get; set; }
        public float HOLD_REQUEST_TIME_SEC { get; set; }
        public float TRIGGERS_DOWN_TO_RUN_WHEN_MOVE { get; set; }
        public float MIN_DIST_TO_RUN_WHILE_ATTACK_MOVING { get; set; }
        public float MIN_DIST_TO_RUN_WHILE_ATTACK_MOVING_OTHER_ENEMIS { get; set; }
        public float MIN_DIST_TO_STOP_RUN { get; set; }
        public float JUMP_SPREAD_DIST { get; set; }
        public float LOOK_TIMES_TO_KILL { get; set; }
        public float COME_INSIDE_TIMES { get; set; }
        public float TOTAL_TIME_KILL { get; set; }
        public float TOTAL_TIME_KILL_AFTER_WARN { get; set; }
        public float MOVING_AIM_COEF { get; set; }
        public float VERTICAL_DIST_TO_IGNORE_SOUND { get; set; }
        public float DEFENCE_LEVEL_SHIFT { get; set; }
        public float MIN_DIST_CLOSE_DEF { get; set; }
        public bool USE_ID_PRIOR_WHO_GO { get; set; }
        public float SMOKE_GRENADE_RADIUS_COEF { get; set; }
        public float GRENADE_PRECISION { get; set; }
        public float MAX_WARNS_BEFORE_KILL { get; set; }
        public float CARE_ENEMY_ONLY_TIME { get; set; }
        public float MIDDLE_POINT_COEF { get; set; }
        public bool MAIN_TACTIC_ONLY_ATTACK { get; set; }
        public float LAST_DAMAGE_ACTIVE { get; set; }
        public bool SHALL_DIE_IF_NOT_INITED { get; set; }
        public float CHECK_BOT_INIT_TIME_SEC { get; set; }
        public float WEAPON_ROOT_Y_OFFSET { get; set; }
        public float DELTA_SUPRESS_DISTANCE_SQRT { get; set; }
        public float DELTA_SUPRESS_DISTANCE { get; set; }
        public float WAVE_COEF_LOW { get; set; }
        public float WAVE_COEF_MID { get; set; }
        public float WAVE_COEF_HIGH { get; set; }
        public float WAVE_COEF_HORDE { get; set; }
        public bool WAVE_ONLY_AS_ONLINE { get; set; }
        public float LOCAL_BOTS_COUNT { get; set; }
        public float AXE_MAN_KILLS_END { get; set; }
    }
}
